on: [push]

env:
  EXPORTER_RUN_FROM_CI: True
  EXPORTER_RELEASE_STRATEGY: "${{ startsWith(github.ref, 'refs/tags/') && 'tag' || 'commit' }}"

jobs:
  run-exporter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      # Checkout your *current* repo
      - uses: actions/checkout@v3
        name: Checkout Current Repository

      # Checkout the TeslaSCIToolkit repo
      - name: Checkout TeslaSCIToolkit
        uses: actions/checkout@v3
        with:
          repository: sci2zero/TeslaSCIToolkit
          path: tesci

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e tesci

      - name: Verify tesci works
        run: |
          tesci --help