description: >
  "Download and release aggregated works from OpenAlex for the Faculty of Technical Sciences, University of Novi Sad, 2023-2025"

download:
  provider: "openalex"
  # for faster download, update your email address in the url instead of <YOUR_EMAIL_ADDRESS>
  url: "https://api.openalex.org/works?page=1&filter=authorships.institutions.lineage:i170726198,raw_affiliation_strings.search:Faculty+of+Technical+Sciences,publication_year:2023-2025&sort=relevance_score:desc&per_page=200&mailto=nikolic.dusan@uns.ac.rs"
  dest: "openalex-fac-tech-sci-2023-2025.csv"

data:
  src: openalex-fac-tech-sci-2023-2025.csv
  dest: openalex-fac-tech-sci-aggregations.csv

aggregate:
  - alias: count_publications_by_year
    columns:
      - id
      - publication_year
    function: count
    grouped: publication_year

  - alias: sum_citations_by_year
    columns:
      - cited_by_count
    function: sum
    grouped: publication_year

  - alias: sum_apc_by_year
    columns:
      - apc_paid.value_usd
    function: sum
    grouped: publication_year

  - alias: top10_percent_publications_by_year
    columns:
      - citation_normalized_percentile.is_in_top_10_percent
    function: sum
    grouped: publication_year

  # - alias: count_oa_vs_closed
  #   columns:
  #     - id
  #   function: count
  #   grouped:
  #     - open_access.is_oa
  #     - publication_year

  # - alias: count_top10_percent_by_oa_and_year
  #   columns:
  #     - citation_normalized_percentile.is_in_top_10_percent
  #   function: sum
  #   grouped:
  #     - publication_year
  #     - open_access.is_oa

  # - alias: avg_citations_by_oa_and_year
  #   columns:
  #     - cited_by_count
  #   function: avg
  #   grouped:
  #     - publication_year
  #     - open_access.is_oa

release:
  - url: https://github.com/n-dusan/fac-tech-sci-demo
    strategy: commit